#!/bin/bash
# Lazy-loading wrappers for support/lazy/* generated by install.sh

# support/lazy/certutils.sh
cert_extract() { unset -f cert_extract; source ~/dotfiles/support/lazy/certutils.sh; cert_extract "$@"; }
cert_label() { unset -f cert_label; source ~/dotfiles/support/lazy/certutils.sh; cert_label "$@"; }
cert_label_hoist() { unset -f cert_label_hoist; source ~/dotfiles/support/lazy/certutils.sh; cert_label_hoist "$@"; }
cert_nickname() { unset -f cert_nickname; source ~/dotfiles/support/lazy/certutils.sh; cert_nickname "$@"; }
cert_sign() { unset -f cert_sign; source ~/dotfiles/support/lazy/certutils.sh; cert_sign "$@"; }
  md5() { unset -f   md5; source ~/dotfiles/support/lazy/certutils.sh;   md5 "$@"; }


# support/lazy/emacs.sh
ediff() { unset -f ediff; source ~/dotfiles/support/lazy/emacs.sh; ediff "$@"; }
emacs_repair() { unset -f emacs_repair; source ~/dotfiles/support/lazy/emacs.sh; emacs_repair "$@"; }
emacs_repair_heavy() { unset -f emacs_repair_heavy; source ~/dotfiles/support/lazy/emacs.sh; emacs_repair_heavy "$@"; }
ensure_ev_daemon() { unset -f ensure_ev_daemon; source ~/dotfiles/support/lazy/emacs.sh; ensure_ev_daemon "$@"; }
gm_smerge_all() { unset -f gm_smerge_all; source ~/dotfiles/support/lazy/emacs.sh; gm_smerge_all "$@"; }
smerge() { unset -f smerge; source ~/dotfiles/support/lazy/emacs.sh; smerge "$@"; }
alias ev="emacs" # -l ~/.emacs.d/ev-init.el"
alias evw="emacsw" # -l ~/.emacs.d/ev-init.el"
alias ec="ensure_ev_daemon; emacsclient --create-frame -nw -t --eval '(menu-bar-mode -1)'"
alias ecw="ensure_ev_daemon; $(getbin emacsclientw emacsclient-w32 emacsclient) --create-frame --eval '(menu-bar-mode 1)'"
alias magit='ec --eval "(progn (magit) (delete-other-windows))"'

# support/lazy/ffmpeg.sh
ffmpeg_clip() { unset -f ffmpeg_clip; source ~/dotfiles/support/lazy/ffmpeg.sh; ffmpeg_clip "$@"; }
ffmpeg_clip_compress() { unset -f ffmpeg_clip_compress; source ~/dotfiles/support/lazy/ffmpeg.sh; ffmpeg_clip_compress "$@"; }
ffmpeg_compress() { unset -f ffmpeg_compress; source ~/dotfiles/support/lazy/ffmpeg.sh; ffmpeg_compress "$@"; }
alias discordmp4="ffmpeg_compress"

# support/lazy/file-management.sh
copybf() { unset -f copybf; source ~/dotfiles/support/lazy/file-management.sh; copybf "$@"; }
copyf() { unset -f copyf; source ~/dotfiles/support/lazy/file-management.sh; copyf "$@"; }
copytardir() { unset -f copytardir; source ~/dotfiles/support/lazy/file-management.sh; copytardir "$@"; }
ddimage() { unset -f ddimage; source ~/dotfiles/support/lazy/file-management.sh; ddimage "$@"; }
delete_empty_dirs() { unset -f delete_empty_dirs; source ~/dotfiles/support/lazy/file-management.sh; delete_empty_dirs "$@"; }
delete_empty_dirs_in() { unset -f delete_empty_dirs_in; source ~/dotfiles/support/lazy/file-management.sh; delete_empty_dirs_in "$@"; }
extract_flatten_all() { unset -f extract_flatten_all; source ~/dotfiles/support/lazy/file-management.sh; extract_flatten_all "$@"; }
extractto() { unset -f extractto; source ~/dotfiles/support/lazy/file-management.sh; extractto "$@"; }
extracttoself() { unset -f extracttoself; source ~/dotfiles/support/lazy/file-management.sh; extracttoself "$@"; }
find_sparse_directories() { unset -f find_sparse_directories; source ~/dotfiles/support/lazy/file-management.sh; find_sparse_directories "$@"; }
flatten_all_in() { unset -f flatten_all_in; source ~/dotfiles/support/lazy/file-management.sh; flatten_all_in "$@"; }
makebak() { unset -f makebak; source ~/dotfiles/support/lazy/file-management.sh; makebak "$@"; }
pastebf() { unset -f pastebf; source ~/dotfiles/support/lazy/file-management.sh; pastebf "$@"; }
pastef() { unset -f pastef; source ~/dotfiles/support/lazy/file-management.sh; pastef "$@"; }
pull_out_oneoffs_in() { unset -f pull_out_oneoffs_in; source ~/dotfiles/support/lazy/file-management.sh; pull_out_oneoffs_in "$@"; }
sedic() { unset -f sedic; source ~/dotfiles/support/lazy/file-management.sh; sedic "$@"; }
sluggify() { unset -f sluggify; source ~/dotfiles/support/lazy/file-management.sh; sluggify "$@"; }
splitpath() { unset -f splitpath; source ~/dotfiles/support/lazy/file-management.sh; splitpath "$@"; }
tarbak() { unset -f tarbak; source ~/dotfiles/support/lazy/file-management.sh; tarbak "$@"; }
toggledisabled() { unset -f toggledisabled; source ~/dotfiles/support/lazy/file-management.sh; toggledisabled "$@"; }


# support/lazy/git.sh
git_cherry_pick_jira() { unset -f git_cherry_pick_jira; source ~/dotfiles/support/lazy/git.sh; git_cherry_pick_jira "$@"; }
git_clone_or_update() { unset -f git_clone_or_update; source ~/dotfiles/support/lazy/git.sh; git_clone_or_update "$@"; }
git_log_search() { unset -f git_log_search; source ~/dotfiles/support/lazy/git.sh; git_log_search "$@"; }
git_migrate_http() { unset -f git_migrate_http; source ~/dotfiles/support/lazy/git.sh; git_migrate_http "$@"; }
gm_add_their_additions() { unset -f gm_add_their_additions; source ~/dotfiles/support/lazy/git.sh; gm_add_their_additions "$@"; }
gm_rm_our_additions() { unset -f gm_rm_our_additions; source ~/dotfiles/support/lazy/git.sh; gm_rm_our_additions "$@"; }
gm_rm_their_deletions() { unset -f gm_rm_their_deletions; source ~/dotfiles/support/lazy/git.sh; gm_rm_their_deletions "$@"; }
gm_wassup() { unset -f gm_wassup; source ~/dotfiles/support/lazy/git.sh; gm_wassup "$@"; }
alias autosquash='git rebase --interactive --autosquash $(git rev-parse origin/HEAD)'
alias git_purge_branches='git_old_local_branches | while read r; do echo $r; git branch -d $r; done'

# support/lazy/hyperloop.sh
hyperloop() { unset -f hyperloop; source ~/dotfiles/support/lazy/hyperloop.sh; hyperloop "$@"; }
hyperl_test_nesting() { unset -f hyperl_test_nesting; source ~/dotfiles/support/lazy/hyperloop.sh; hyperl_test_nesting "$@"; }


# support/lazy/meta.sh
  _extractfont() { unset -f   _extractfont; source ~/dotfiles/support/lazy/meta.sh;   _extractfont "$@"; }
shhelp() { unset -f shhelp; source ~/dotfiles/support/lazy/meta.sh; shhelp "$@"; }
shtranslate() { unset -f shtranslate; source ~/dotfiles/support/lazy/meta.sh; shtranslate "$@"; }

