#!/bin/bash

# ~/.bashrc: executed by bash(1) for each interactive non-login shell.
# Also invoked manually by .bash_profile for interactive login shells
# This file is for globals

if [ -n "$TMOUT" ]; then
  echo "Detected ephemeral shell, bootstrapping real session."
  exec env TMOUT= bash
fi

## Global script utils

# Munge an entry into an environment variable list
# like PATH or PROMPT_COMMAND
envmunge () {
  _var=$1
  _val=$2
  _sep=${3:-:}
  _pos=${4:-:}
  case "${_sep}${!_var}${_sep}" in
    *${_sep}"$_val"${_sep}*)
      ;;
    *)
      if [ -z "${!_var}" ]; then
        # Empty
        printf -v "$_var" '%s' "${_val}"
      else
        # Not empty
        if [ "$_pos" = "after" ] ; then
          printf -v "$_var" '%s' "${!_var}${_sep}${_val}"
        else
          printf -v "$_var" '%s' "${_val}${_sep}${!_var}"
        fi
      fi
  esac
}

pathmunge() { envmunge PATH "$1" ':' ${2:-}; }

sourceif () {
  [[ -f "$1" ]] && . "$1"; # || echo "missing file $1";
}

# Copy a bash function
copy_function () {
  local ORIG_FUNC=$(declare -f $1)
  # local NEWNAME_FUNC="$2${ORIG_FUNC#$1}"
  # eval "$NEWNAME_FUNC"
  eval "$2${ORIG_FUNC#$1}"
}

# Find the first real executable in a list, prioritizing user files and then system builtins instead of PATH order.
getbin () {
  for q in $@; do
    for p in "$HOME/.local/bin/" '/usr/bin/' '/bin/' ''; do
      which "$p$q" &>/dev/null && echo "$p$q" && return
    done
  done
}
export -f getbin

# Find best hostname, remove trailing .
export HOSTNAME="$($(getbin hostname) -f 2>/dev/null | sed 's/\.$//' || cat /etc/hostname )"

## User functions, locals
source ~/dotfiles/support/colors.sh
source ~/dotfiles/support/personal.sh

# Lazy-loaded modules (generated by install.sh)
source ~/dotfiles/support/_lazyload.sh

# Source specifics for OS
sourceif ~/dotfiles/local/.bashrc_$(uname -o | sed 's/[^a-zA-Z0-9]/_/g')

# Source specifics for HOST or DOMAIN
for localrc in ~/dotfiles/local/.bashrc_*; do
  # Chop suffix from rc filename
  localrc_suffix="${localrc##~/dotfiles/local/.bashrc_}"
  # Source if HOSTNAME ends with SUFFIX
  [[ "$HOSTNAME" == *"${localrc_suffix}" ]] && sourceif "$localrc"
done

# Source manual local file
sourceif ~/.bashrc_local

# Ready for interactivity
source ~/dotfiles/support/prompt.sh

