name: Publish Git Bundle Release

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'

jobs:
  github-release:
    runs-on: ubuntu-slim

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        # critical: full history
          fetch-tags: true      # include all tags too

      - name: Create Git Bundle
        run: git bundle create repo.bundle --all

      - name: Verify bundle
        run: git bundle verify repo.bundle   # will catch gaps before uploading

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        continue-on-error: true
        run: >-
          gh release create
          "$(date +'%Y-%m-%d')"
          --repo '${{ github.repository }}'
          --notes "" --prerelease

      - name: Upload artifact signatures to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release upload
          "$(date +'%Y-%m-%d')"
          repo.bundle
          --repo '${{ github.repository }}'
          --clobber
